name: Create Debian Package

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build in container
        run: docker build -f ${{github.workspace}}/Dockerfile . --target package -t temp-image

      - name: Build temp container
        run: docker create --name temp-container temp-image

      - name: Copy Package
        run: mkdir ${{github.workspace}}/package/ && docker cp temp-container:/package/ ${{github.workspace}}/

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: creature-server-package-${{ matrix.os }}
          path: ${{github.workspace}}/package/
